[theme]
base = "light"
primaryColor = "#81B29A"  # Cambridge Blue
backgroundColor = "#FFF5F5" # Snow (Warm White)
secondaryBackgroundColor = "#FFFFFF"
textColor = "#27231E" # Eerie Black
font = "sans serif"
